# Generated by Django 3.0.3 on 2020-08-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_user_jwtsecret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='jwtSecret',
            new_name='jwt_secret',
        ),
    ]
