# Generated by Django 3.0.3 on 2020-08-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200823_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jwt_secret',
        ),
    ]
