# Generated by Django 3.0.3 on 2020-09-02 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_inventory_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
    ]
