# Generated by Django 3.0.3 on 2020-09-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_user_total_spins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tq_unboxed',
            field=models.IntegerField(default=0),
        ),
    ]
