# Generated by Django 3.0.3 on 2020-09-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_user_tq_unboxed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='items_found',
            field=models.IntegerField(default=0),
        ),
    ]
