# Generated by Django 3.0.3 on 2020-09-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_auto_20200904_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='in_circulation',
            field=models.IntegerField(default=0),
        ),
    ]
