# Generated by Django 3.0.3 on 2020-09-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_item_in_circulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='common_unboxed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='epic_unboxed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='godly_unboxed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='holy_unboxed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rare_unboxed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='uncommon_unboxed',
            field=models.IntegerField(default=0),
        ),
    ]
