# Generated by Django 3.0.3 on 2020-09-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_auto_20200908_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=128),
        ),
    ]
