# Generated by Django 3.0.3 on 2020-12-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_marketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
