# Generated by Django 3.0.3 on 2020-12-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_auto_20201228_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='listTime',
            field=models.IntegerField(default=0),
        ),
    ]
