# Generated by Django 3.0.3 on 2021-01-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_marketitem_listtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedjwt',
            name='exp_time',
            field=models.IntegerField(default=0, max_length=128),
        ),
    ]
