# Generated by Django 4.0.4 on 2022-11-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credits',
            new_name='Credit',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
