# Generated by Django 4.0.4 on 2022-11-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0004_rename_credit_projectcredit_alter_imagelink_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_link',
            new_name='image_links',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_link',
            new_name='project_links',
        ),
    ]
