# Generated by Django 4.0.4 on 2022-12-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0005_rename_image_link_project_image_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_name',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
