# Generated by Django 4.0.4 on 2022-12-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0006_project_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url_name',
            field=models.CharField(default=models.CharField(max_length=32, unique=True), max_length=32, unique=True),
        ),
    ]
