# Generated by Django 4.0.4 on 2022-12-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0008_alter_project_options_project_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url_name',
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
