# Generated by Django 4.0.4 on 2022-12-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0010_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlink',
            name='type',
            field=models.CharField(choices=[('WEB', 'Website'), ('GIT', 'GitHub')], default='WEB', max_length=3),
        ),
    ]
