# Generated by Django 4.0.4 on 2022-12-22 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0011_projectlink_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('proficiency', models.CharField(choices=[('BAS', 'Basic'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], default='BAS', max_length=3)),
                ('image_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jerrytq.imagelink')),
            ],
        ),
    ]
