# Generated by Django 4.0.4 on 2022-12-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0012_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='jerrytq.skill'),
        ),
    ]
