# Generated by Django 4.0.4 on 2022-12-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0013_project_technologies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
    ]
