# Generated by Django 4.0.4 on 2022-12-24 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0015_alter_skill_options_remove_skill_image_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCreditToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='credits',
        ),
        migrations.AddField(
            model_name='project',
            name='project_credits',
            field=models.ManyToManyField(through='jerrytq.ProjectCreditToProject', to='jerrytq.projectcredit'),
        ),
        migrations.AddField(
            model_name='projectcredittoproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jerrytq.project'),
        ),
        migrations.AddField(
            model_name='projectcredittoproject',
            name='project_credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jerrytq.projectcredit'),
        ),
    ]
