# Generated by Django 4.0.4 on 2022-12-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0017_imagelinktoproject_technologytoproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='type',
            field=models.CharField(choices=[('LAN', 'Language'), ('FRA', 'Framework'), ('LIB', 'Library'), ('TOO', 'Tool'), ('PLA', 'Platform')], default='LAN', max_length=3),
        ),
    ]
