# Generated by Django 4.0.4 on 2022-12-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0018_alter_technology_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
