# Generated by Django 4.0.4 on 2022-12-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0019_alter_imagelink_name_alter_projectlink_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
