# Generated by Django 4.0.4 on 2022-12-30 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jerrytq', '0022_alter_term_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
