# Generated by Django 4.1 on 2024-12-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jerrytq", "0025_alter_project_project_links_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="short_description",
            field=models.TextField(default="", max_length=32),
        ),
    ]
