# Generated by Django 3.0.3 on 2020-08-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
