# Generated by Django 3.0.3 on 2020-08-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0002_auto_20200823_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwtSecret',
            field=models.CharField(default='secret', max_length=256),
        ),
    ]
