# Generated by Django 3.0.3 on 2020-08-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0006_blacklistedjwt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='SP',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blacklistedjwt',
            name='jwt',
            field=models.CharField(max_length=512),
        ),
    ]
