# Generated by Django 3.0.3 on 2020-09-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0009_auto_20200902_0410'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='InventoryItem',
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={},
        ),
    ]
