# Generated by Django 3.0.3 on 2020-09-02 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0010_auto_20200902_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spin.User'),
        ),
    ]
