# Generated by Django 3.0.3 on 2020-09-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0011_auto_20200902_0523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
    ]
