# Generated by Django 3.0.3 on 2020-09-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0013_auto_20200903_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_spins',
            field=models.IntegerField(default=0),
        ),
    ]
