# Generated by Django 3.0.3 on 2020-09-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0019_auto_20200905_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_free_sp_time',
            field=models.FloatField(default=0),
        ),
    ]
