# Generated by Django 3.0.3 on 2020-09-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0020_user_last_free_sp_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='SP',
            new_name='sp',
        ),
        migrations.AddField(
            model_name='user',
            name='net_sp',
            field=models.IntegerField(default=0),
        ),
    ]
