# Generated by Django 3.0.3 on 2020-12-28 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0024_marketitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spin.Item'),
        ),
    ]
