# Generated by Django 3.0.3 on 2020-12-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0025_auto_20201228_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketitem',
            options={'ordering': ['user', 'item', 'price']},
        ),
    ]
