# Generated by Django 3.0.3 on 2021-01-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0028_blacklistedjwt_exp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedjwt',
            name='exp_time',
            field=models.IntegerField(default=0),
        ),
    ]
