# Generated by Django 4.0.4 on 2022-07-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0029_auto_20210102_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedjwt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
