# Generated by Django 4.0.4 on 2022-09-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0030_alter_blacklistedjwt_id_alter_inventoryitem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='items_found',
        ),
    ]
